name: Add Contributor

on:
  pull_request:
    types: [closed]

jobs:
  add-contributor:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Add contributor to file
      run: |
        # Check if the contributor is already in the Contributors.md file
        if ! grep -q "@${{ github.actor }}" Contributors.md; then
          # If not, append the contributor's name to the file
          echo "- @${{ github.actor }}" >> Contributors.md
          git add Contributors.md
          git commit -m "chore: add contributor ${{ github.actor }}"
          git push
        else
          # If already added, do nothing and print a message
          echo "Contributor @${{ github.actor }} is already in the file. Skipping."
        fi
